apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: devops
  ports:
    - protocol: TCP
      port: 80  # Port d’accès depuis l'extérieur
      targetPort: 3000  # Port de l'application dans le conteneur
  type: LoadBalancer
